; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensymm]
platform = teensy
board = teensymm
board_build.f_cpu = 150000000L
framework = arduino
lib_deps = 
	Wire
	CayenneLPP
	adafruit/Adafruit TSL2591 Library@^1.4.5
build_flags = -D USB_MIDI_AUDIO_SERIAL -D WAIT_FOR_SERIAL
test_ignore = test_desktop

[env:teensymm-release]
platform = teensy
board = teensymm
board_build.f_cpu = 150000000L
framework = arduino
lib_deps = 
	Wire
	CayenneLPP
	adafruit/Adafruit TSL2591 Library@^1.4.5
build_flags = -D USB_AUDIO
test_ignore = test_desktop

[env:desktop]
platform = native
lib_extra_dirs = 
	lib/
	include/
test_ignore = test_embedded
build_flags = -D DESKTOP_NATIVE
lib_deps = adafruit/Adafruit TSL2591 Library@^1.4.5
