#!/usr/bin/env python3
"""Compare bait_new_indices.csv against soundecology_new_indices.csv and write RESULTS.md."""
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import spearmanr

HERE = Path(__file__).resolve().parent

INDICES = [
    ("bi", "Bioacoustic Index", "soundecology::bioacoustic_index"),
    ("hf", "Spectral entropy Hf", "seewave::sh(meanspec())"),
    ("ht", "Temporal entropy Ht", "seewave::th(env(envt = \"hil\"))"),
    ("h", "Total entropy H = Ht x Hf", "seewave::H"),
    ("events", "Acoustic event count", "two-pass count in R (no published reference)"),
]


def stats(bait, ref):
    rel = np.abs(bait - ref) / np.abs(ref)
    rho = spearmanr(bait, ref).statistic
    return f"{np.median(rel) * 100:.2f}% | {rel.max() * 100:.2f}% | {rho:.3f}"


def main():
    bait = pd.read_csv(HERE / "bait_new_indices.csv")
    ref = pd.read_csv(HERE / "soundecology_new_indices.csv")
    df = bait.merge(ref, on=["file", "file_number"])

    lines = [
        "# New indices vs. soundecology / seewave",
        "",
        "Generated by `compare_new_indices.py` from the 50 files in `../SOUND/`. See `README.md`.",
        "",
        "Each cell is: median |relative difference| | max |relative difference| | Spearman rho.",
        "",
        "| Index | Reference | BAIT maths, reference frames | BAIT maths, Teensy-style frames |",
        "|---|---|---|---|",
    ]
    for key, name, source in INDICES:
        lines.append(
            f"| {name} | `{source}` | {stats(df[f'reference_{key}'], df[key])} "
            f"| {stats(df[f'teensy_{key}'], df[key])} |"
        )

    exact = (df["reference_events"] == df["events"]).sum()
    lines += [
        "",
        f"Event counts identical to the R two-pass count (reference frames): {exact} / {len(df)} files.",
        "",
        "## Per-file values",
        "",
        "| File | BI ref | BI BAIT (ref frames) | BI BAIT (Teensy) | H ref | H BAIT (ref frames) | H BAIT (Teensy) "
        "| Events ref | Events BAIT (ref frames) | Events BAIT (Teensy) |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for _, r in df.iterrows():
        lines.append(
            f"| {r.file_number} | {r.bi:.4f} | {r.reference_bi:.4f} | {r.teensy_bi:.4f} "
            f"| {r.h:.4f} | {r.reference_h:.4f} | {r.teensy_h:.4f} "
            f"| {int(r.events)} | {int(r.reference_events)} | {int(r.teensy_events)} |"
        )

    (HERE / "RESULTS.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines[:16]))


if __name__ == "__main__":
    main()
